name: Deploy to Heroku

on:
  push:
    branches: [main]

#set environment variables
env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ 'travel-guardian' }}

jobs:
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-18.04
    steps:
      # Clone the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Build Docker image
      - name: Docker build
        run: docker login --${{ secrets.DOCKER_USERNAME }}=_ --${{ secrets.DOCKER_PASSWORD }}=$HEROKU_API_KEY registry.heroku.com

      # Push the Docker image to Heroku Container Registry
      - name: Publish
        run: |
          heroku container:push web -a travel-guardian
          heroku container:release web -a travel-guardian
